version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/peerlearn
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=peerlearn
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A peerlearn worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/peerlearn
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A peerlearn beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/peerlearn
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: