# Generated by Django 5.2.1 on 2025-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the domain/category.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this domain/category.', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for this domain (e.g., "code" for programming).', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this domain was created.')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='domain',
            field=models.ForeignKey(help_text='Domain or category of the requested session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_requests', to='learning_sessions.domain'),
        ),
    ]
