# Generated by Django 5.2.1 on 2025-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0003_alter_sessionrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this session is being offered for free.'),
        ),
    ]
