# Generated by Django 5.2.1 on 2025-05-13 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The notification message.')),
                ('link', models.CharField(blank=True, help_text='Link to redirect the user to when clicked.', max_length=255, null=True)),
                ('read', models.BooleanField(default=False, help_text='Whether the notification has been read.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the notification was created.')),
                ('user', models.ForeignKey(help_text='The user to whom the notification is sent.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
