# Generated by Django 5.2.1 on 2025-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='The type of notification.', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, help_text='Optional reference ID for related object (session, booking, etc).', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='The notification title.', max_length=255, null=True),
        ),
    ]
